# Generated by Django 4.2.11 on 2024-08-13 19:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Complete', 'Complete')], default='Running', max_length=10)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='reports/')),
            ],
        ),
    ]
